// This file is auto-generated by @hey-api/openapi-ts

export const $ExerciseModel = {
    properties: {
        muscle_group_id: {
            type: 'integer',
            title: 'Muscle Group Id'
        },
        muscle_id: {
            type: 'integer',
            title: 'Muscle Id'
        },
        exercise_id: {
            type: 'integer',
            title: 'Exercise Id'
        },
        exercise_name: {
            type: 'string',
            title: 'Exercise Name'
        },
        sets: {
            items: {
                '$ref': '#/components/schemas/back__models__exercise__ExerciseModel__setDetail'
            },
            type: 'array',
            title: 'Sets',
            default: []
        }
    },
    type: 'object',
    required: ['muscle_group_id', 'muscle_id', 'exercise_id', 'exercise_name'],
    title: 'ExerciseModel'
} as const;

export const $ExercisedetailsModel = {
    properties: {
        user_id: {
            type: 'integer',
            title: 'User Id'
        },
        exercise_id: {
            type: 'integer',
            title: 'Exercise Id'
        },
        exercise_details_id: {
            type: 'integer',
            title: 'Exercise Details Id'
        },
        performed_date: {
            type: 'string',
            title: 'Performed Date',
            default: 'Now()'
        },
        sets: {
            items: {
                '$ref': '#/components/schemas/back__models__exerciseDetails__ExercisedetailsModel__setDetail'
            },
            type: 'array',
            title: 'Sets'
        }
    },
    type: 'object',
    required: ['user_id', 'exercise_id', 'exercise_details_id', 'sets'],
    title: 'ExercisedetailsModel'
} as const;

export const $FetchAll = {
    properties: {
        muscle_name: {
            type: 'string',
            title: 'Muscle Name'
        },
        muscle_group_name: {
            type: 'string',
            title: 'Muscle Group Name'
        },
        exercise_name: {
            type: 'string',
            title: 'Exercise Name'
        },
        performed_date: {
            type: 'string',
            title: 'Performed Date'
        },
        user_id: {
            type: 'integer',
            title: 'User Id'
        },
        exercise_id: {
            type: 'integer',
            title: 'Exercise Id'
        },
        exercise_details_id: {
            type: 'integer',
            title: 'Exercise Details Id'
        }
    },
    type: 'object',
    required: ['muscle_name', 'muscle_group_name', 'exercise_name', 'performed_date', 'user_id', 'exercise_id', 'exercise_details_id'],
    title: 'FetchAll'
} as const;

export const $HTTPValidationError = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const $LoginModel = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        password: {
            type: 'string',
            title: 'Password'
        }
    },
    type: 'object',
    required: ['name', 'password'],
    title: 'LoginModel'
} as const;

export const $LoginResponse = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        }
    },
    type: 'object',
    required: ['success'],
    title: 'LoginResponse'
} as const;

export const $MuscleGroupModel = {
    properties: {
        muscle_group_id: {
            type: 'integer',
            title: 'Muscle Group Id'
        },
        muscle_group_name: {
            type: 'string',
            title: 'Muscle Group Name'
        }
    },
    type: 'object',
    required: ['muscle_group_id', 'muscle_group_name'],
    title: 'MuscleGroupModel'
} as const;

export const $MuscleModel = {
    properties: {
        muscle_group_id: {
            type: 'integer',
            title: 'Muscle Group Id'
        },
        muscle_id: {
            type: 'integer',
            title: 'Muscle Id'
        },
        muscle_name: {
            type: 'string',
            title: 'Muscle Name'
        }
    },
    type: 'object',
    required: ['muscle_group_id', 'muscle_id', 'muscle_name'],
    title: 'MuscleModel'
} as const;

export const $UserModel = {
    properties: {
        user_id: {
            type: 'integer',
            title: 'User Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        gender: {
            type: 'string',
            maxLength: 1,
            title: 'Gender'
        },
        age: {
            type: 'integer',
            title: 'Age'
        },
        height: {
            type: 'integer',
            title: 'Height'
        },
        weight: {
            type: 'integer',
            title: 'Weight'
        }
    },
    type: 'object',
    required: ['user_id', 'name', 'password', 'gender', 'age', 'height', 'weight'],
    title: 'UserModel'
} as const;

export const $ValidationError = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const $back__models__exerciseDetails__ExercisedetailsModel__setDetail = {
    properties: {
        set_number: {
            type: 'integer',
            title: 'Set Number'
        },
        weight: {
            type: 'integer',
            title: 'Weight'
        },
        reps: {
            type: 'integer',
            title: 'Reps'
        }
    },
    type: 'object',
    required: ['set_number', 'weight', 'reps'],
    title: 'setDetail'
} as const;

export const $back__models__exercise__ExerciseModel__setDetail = {
    properties: {
        set_number: {
            type: 'integer',
            title: 'Set Number'
        },
        weight: {
            type: 'integer',
            title: 'Weight'
        },
        reps: {
            type: 'integer',
            title: 'Reps'
        }
    },
    type: 'object',
    required: ['set_number', 'weight', 'reps'],
    title: 'setDetail'
} as const;