// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-axios';
import type { ExerciseDetailsFetchSetDetailsData, ExerciseDetailsFetchSetDetailsError, ExerciseDetailsFetchSetDetailsResponse, ExerciseDetailsFetchAllData, ExerciseDetailsFetchAllError, ExerciseDetailsFetchAllResponse, ExerciseDetailsInsertData, ExerciseDetailsInsertError, ExerciseDetailsInsertResponse, MuscleGroupsFetchAllData, MuscleGroupsFetchAllError, MuscleGroupsFetchAllResponse, UsersCreateUserData, UsersCreateUserError, UsersCreateUserResponse, UsersLoginData, UsersLoginError, UsersLoginResponse, MusclesFetchAllData, MusclesFetchAllError, MusclesFetchAllResponse, ExercisesFetchAllData, ExercisesFetchAllError, ExercisesFetchAllResponse, ExercisesFetchNextSetData, ExercisesFetchNextSetError, ExercisesFetchNextSetResponse, ExercisesFetchSetDetailsData, ExercisesFetchSetDetailsError, ExercisesFetchSetDetailsResponse } from './types.gen';

export const client = createClient(createConfig());

export class ExerciseDetailsService {
    /**
     * Fetchsetdetails
     */
    public static detailsFetchSetDetails<ThrowOnError extends boolean = false>(options: Options<ExerciseDetailsFetchSetDetailsData, ThrowOnError>) {
        return (options?.client ?? client).get<ExerciseDetailsFetchSetDetailsResponse, ExerciseDetailsFetchSetDetailsError, ThrowOnError>({
            ...options,
            url: '/exerciseDetails/set'
        });
    }
    
    /**
     * Fetchall
     */
    public static detailsFetchAll<ThrowOnError extends boolean = false>(options?: Options<ExerciseDetailsFetchAllData, ThrowOnError>) {
        return (options?.client ?? client).get<ExerciseDetailsFetchAllResponse, ExerciseDetailsFetchAllError, ThrowOnError>({
            ...options,
            url: '/exerciseDetails/'
        });
    }
    
    /**
     * Insert
     */
    public static detailsInsert<ThrowOnError extends boolean = false>(options: Options<ExerciseDetailsInsertData, ThrowOnError>) {
        return (options?.client ?? client).post<ExerciseDetailsInsertResponse, ExerciseDetailsInsertError, ThrowOnError>({
            ...options,
            url: '/exerciseDetails/'
        });
    }
    
}

export class MuscleGroupsService {
    /**
     * Fetchall
     */
    public static groupsFetchAll<ThrowOnError extends boolean = false>(options?: Options<MuscleGroupsFetchAllData, ThrowOnError>) {
        return (options?.client ?? client).get<MuscleGroupsFetchAllResponse, MuscleGroupsFetchAllError, ThrowOnError>({
            ...options,
            url: '/muscle_groups/'
        });
    }
    
}

export class UsersService {
    /**
     * Createuser
     */
    public static createUser<ThrowOnError extends boolean = false>(options: Options<UsersCreateUserData, ThrowOnError>) {
        return (options?.client ?? client).post<UsersCreateUserResponse, UsersCreateUserError, ThrowOnError>({
            ...options,
            url: '/users/'
        });
    }
    
    /**
     * Login
     */
    public static login<ThrowOnError extends boolean = false>(options: Options<UsersLoginData, ThrowOnError>) {
        return (options?.client ?? client).post<UsersLoginResponse, UsersLoginError, ThrowOnError>({
            ...options,
            url: '/users/login'
        });
    }
    
}

export class MusclesService {
    /**
     * Fetchall
     */
    public static fetchAll<ThrowOnError extends boolean = false>(options?: Options<MusclesFetchAllData, ThrowOnError>) {
        return (options?.client ?? client).get<MusclesFetchAllResponse, MusclesFetchAllError, ThrowOnError>({
            ...options,
            url: '/muscles/'
        });
    }
    
}

export class ExercisesService {
    /**
     * Fetchall
     */
    public static fetchAll<ThrowOnError extends boolean = false>(options?: Options<ExercisesFetchAllData, ThrowOnError>) {
        return (options?.client ?? client).get<ExercisesFetchAllResponse, ExercisesFetchAllError, ThrowOnError>({
            ...options,
            url: '/exercises/'
        });
    }
    
    /**
     * Fetchnextset
     */
    public static fetchNextSet<ThrowOnError extends boolean = false>(options: Options<ExercisesFetchNextSetData, ThrowOnError>) {
        return (options?.client ?? client).get<ExercisesFetchNextSetResponse, ExercisesFetchNextSetError, ThrowOnError>({
            ...options,
            url: '/exercises/set/next'
        });
    }
    
    /**
     * Fetchsetdetails
     */
    public static fetchSetDetails<ThrowOnError extends boolean = false>(options: Options<ExercisesFetchSetDetailsData, ThrowOnError>) {
        return (options?.client ?? client).get<ExercisesFetchSetDetailsResponse, ExercisesFetchSetDetailsError, ThrowOnError>({
            ...options,
            url: '/exercises/set/details'
        });
    }
    
}